apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: providers.db.isotoma.com
spec:
  group: db.isotoma.com
  names:
    kind: Provider
    listKind: ProviderList
    plural: providers
    singular: provider
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
